import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/start/Header";
import Footer from "@/components/start/Footer";
import Container from "@/components/shared/Container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Container>{children}</Container>

      <Script
        src="../components/assets/scripts/core.jquery.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/scripts/plugin.imagesloaded.pkgd.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/scripts/plugin.in-viewport.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/scripts/plugin.animate.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/scripts/plugin.isotope.pkgd.min.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/scripts/plugin.ScrollToPlugin.min.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/scripts/plugin.SplitText.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/scripts/plugin.TweenMax.min.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/scripts/plugin.touchSwipe.min.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/scripts/plugin.typed.min.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/plugins/nevo-slider/nevo-slider.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/plugins/nevo-lightbox/nevo-lightbox.js"
        strategy="lazyOnload"
      />
      <Script
        src="../components/assets/scripts/main.functions.js"
        strategy="lazyOnload"
      />
    </html>
  );
}
